version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "3999:3999"
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"

