# http://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockersFROM node:7.6-alpine

COPY ./*.js /app/
COPY ./*.html /app/
COPY ./*.json /app/
COPY ./src /app/src/

WORKDIR /app

RUN npm i
RUN npm run build

EXPOSE 3000

CMD npm run server-client
